apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::058264145287:role/ra-GithubOIDC-EKS-Role
      username: "system:serviceaccount:default:github-actions"
      groups:
        - system:masters

