name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/radamspdx-wiz/tasky
  AWS_REGION: us-east-2
  EKS_CLUSTER_NAME: ra-wiz-ekscluster4

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  deploy-to-eks:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:

      - name: Debug GitHub OIDC Token
        run: |
          echo "Fetching GitHub OIDC Token..."
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "Raw Token: $TOKEN"
          echo "Decoded Token:"
          echo $TOKEN | jq -R 'split(".") | .[1] | @base64d' | jq

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::058264145287:role/ra-GithubOIDC-EKS-Role
          role-session-name: GitHubActionsSession
          aws-region: us-east-2
          audience: sts.amazonaws.com
      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Update Deployment with New Image
        run: |
          kubectl set image deployment/tasky-deployment tasky-container=$IMAGE_NAME:${{ env.IMAGE_TAG }} -n default
          kubectl rollout restart deployment/tasky-deployment -n default
